baseURL = "https://hardcore-torvalds-9ff568.netlify.app/"
languageCode = "en-us"
title = "Komunitas Pecinta Musik Religi Semarang"
theme = "nasyidsemarang"
summaryLength = 10
paginate = 2

[params]
    Description = "komunitas pecinta nasyid"